variable "gallery-name" { default = "VMMasterGallery" }
variable "image-name" { default = "UbuntuProntusMaster" }
variable "resource-group" { default = "VMMasterGallery-RG" }
variable "subscription-id" { default = "dc7a0e24-be24-4628-a06e-efd67a37b68f" }

## image source variables ##
variable "image-offer" { default = "UbuntuServer" }
variable "image-publisher" { default = "Canonical" }
variable "image-sku" { default = "20.04-LTS" }
variable "image-version" { default = "latest" }

source "azure-chroot" "autogenerated_1" {
#  client_id     = "${var.client_id}"
#  client_secret = "${var.client_secret}"
  shared_image_destination {
    exclude_from_latest = false
    gallery_name        = "${var.gallery-name}"
    image_name          = "${var.image-name}"
    image_version       = "1.0.0"
    resource_group      = "${var.resource-group}"
    target_regions {
      name                 = "eastus"
      replicas             = "1"
      storage_account_type = "standard_zrs"
    }
  }
  source          = "${var.image-publisher}:${var.image-offer}:${var.image-sku}:${var.image-version}"
  subscription_id = "${var.subscription-id}"
}

build {
  sources = ["source.azure-chroot.autogenerated_1"]

  provisioner "shell" {
    inline         = ["apt update", "apt upgrade -y"]
    inline_shebang = "/bin/sh -x"
  }

}
